version: '3'

services:
  dockerapi:
    container_name: agsr_api
    image: agsr_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings_Default: host=agsr_postgres_image;port=5432;database=postgres;username=dbuser;password=dbuser;
      CONNECTIONSTRINGS__DEFAULT: host=agsr_postgres_image;port=5432;database=postgres;username=dbuser;password=dbuser;
      ConnectionStrings__DefaultConnection: host=agsr_postgres_image;port=5432;database=postgres;username=dbuser;password=dbuser;
#    networks:
#      - test-network

  postgres_image:
    container_name: agsr_postgres_image
    image: postgres:15.3
    ports:
      - "5015:5432"
    environment:
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbuser"
      POSTGRES_DB: "postgres"
#    networks:
#      - test-network

#networks:
#  test-network:
#    driver: bridge